const destinations = [
    {
    name: { type: String, required: true },
    photo: { type: String, required: true },
    rating: { type: String, required: true },
    description: { type: String, required: true },
    averageCost: { type: String, required: true },
    thingsToDo: [],
    coworkingSpaces: [],
    transportation: [], 
    },
    {
    name: { type: String, required: true },
    photo: { type: String, required: true },
    rating: { type: String, required: true },
    description: { type: String, required: true },
    averageCost: { type: String, required: true },
    thingsToDo: [],
    coworkingSpaces: [],
    transportation: [], 
    },
    {
    name: { type: String, required: true },
    photo: { type: String, required: true },
    rating: { type: String, required: true },
    description: { type: String, required: true },
    averageCost: { type: String, required: true },
    thingsToDo: [],
    coworkingSpaces: [],
    transportation: [], 
    },
    {
    name: { type: String, required: true },
    photo: { type: String, required: true },
    rating: { type: String, required: true },
    description: { type: String, required: true },
    averageCost: { type: String, required: true },
    thingsToDo: [],
    coworkingSpaces: [],
    transportation: [], 
    },
    {
    name: { type: String, required: true },
    photo: { type: String, required: true },
    rating: { type: String, required: true },
    description: { type: String, required: true },
    averageCost: { type: String, required: true },
    thingsToDo: [],
    coworkingSpaces: [],
    transportation: [], 
    },
    {
    name: { type: String, required: true },
    photo: { type: String, required: true },
    rating: { type: String, required: true },
    description: { type: String, required: true },
    averageCost: { type: String, required: true },
    thingsToDo: [],
    coworkingSpaces: [],
    transportation: [],    
    }
]

// Export the seed data to `models/index.js`
module.exports = dests